# Generated by Django 4.2.3 on 2023-07-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0002_spot"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="spot",
            name="cover_charge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="spot",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spot",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="spot",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="spot",
            name="affiliate_apps",
            field=models.ManyToManyField(blank=True, to="page.affiliateapp"),
        ),
        migrations.AddField(
            model_name="spot",
            name="location_types",
            field=models.ManyToManyField(blank=True, to="page.locationtype"),
        ),
        migrations.AddField(
            model_name="spot",
            name="tags",
            field=models.ManyToManyField(blank=True, to="page.tag"),
        ),
    ]
