# Generated by Django 4.2.3 on 2023-07-26 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0003_affiliateapp_locationtype_tag_spot_cover_charge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="spot_images/")),
                ("is_main_image", models.BooleanField(default=False)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="page.spot",
                    ),
                ),
            ],
        ),
    ]
