# Generated by Django 4.2.3 on 2023-08-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drycana", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spot",
            name="affiliate_apps",
            field=models.ManyToManyField(
                blank=True, related_name="spots", to="drycana.affiliateapp"
            ),
        ),
        migrations.AlterField(
            model_name="spot",
            name="location_types",
            field=models.ManyToManyField(
                blank=True, related_name="spots", to="drycana.locationtype"
            ),
        ),
        migrations.AlterField(
            model_name="spot",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="spots", to="drycana.tag"
            ),
        ),
    ]
