# Generated by Django 4.2.3 on 2023-08-09 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "drycana",
            "0002_alter_spot_affiliate_apps_alter_spot_location_types_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spot",
            name="affiliate_apps",
        ),
        migrations.CreateModel(
            name="SpotAffiliate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "affiliate_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drycana.affiliateapp",
                    ),
                ),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drycana.spot"
                    ),
                ),
            ],
            options={
                "unique_together": {("spot", "affiliate_app")},
            },
        ),
    ]
