# Generated by Django 4.2.3 on 2023-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "drycana",
            "0004_spot_friday_close_spot_friday_open_spot_monday_close_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeInterpreter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("SQL", "SQL"), ("Python", "Python")], max_length=10
                    ),
                ),
                ("code", models.TextField()),
                ("result", models.TextField(blank=True, null=True)),
                ("table", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
