# Generated by Django 4.2.3 on 2023-09-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drycana", "0005_codeinterpreter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeinterpreter",
            name="table",
            field=models.CharField(max_length=255),
        ),
    ]
